### ISSUE TITLE
What is an "Octect key"?

### ISSUE THREAD

**Issue by thanatos** [lawliet89/biscuit#118]
E.g., in [`KeyType`](https://lawliet89.github.io/biscuit/biscuit/jwk/enum.KeyType.html#variant.Octect), but it appears in numerous other function names, etc.

Is this a misspelling of "octet"?

**Comment by lawliet89** [comment]
You're right. It's a misspelling 🤦‍♂️

I'll fix that in the future but it's going to be a breaking change.

**Comment by thanatos** [comment]
> I'll fix that in the future 

Thank you! In a crypto crate, it's not exactly what one wants to see.

> but it's going to be a breaking change.

Unfortunately. I wonder if it could be made more gentle by doing the rename, and then leaving being functions that just simple call the correctly named version, but with a `
#[deprecated()]` attribute? E.g.,

```rust
fn foo_octect(Args...) {
    foo_octet(Args...)
}
fn foo_octect(Args...) {
    // the real function
}
```

And for the enumeration, an associated constant, e.g.,
```rust
enum KeyType {
    ...
    /// Octet sequence, representing symmetric keys
    #[serde(rename = "oct")]
    Octet,
    ...
}

impl KeyType {
    #[deprecated(...)]
    pub const Octect: KeyType = KeyType::Octet;
}
```

I *think* that shouldn't cause breakage, but I'm not 100% sure. Then, in semver-breaking crate, e.g., `0.4`, the deprecated names could be dropped.

Up to you, as I'm not sure how much value it provides over just letting semver do its thing.

**Comment by lawliet89** [comment]
I am going to do a breaking change in 0.4.0. There is too much duplicate logic to supporting both sets of enum variants. 

The migration is a relatively simple search and replace anyway.
