### ISSUE TITLE
decode_with_jwks failing when alg missing

### ISSUE THREAD

**Issue by ccakes** [lawliet89/biscuit#127]
The published [MSFT JWKs](https://login.microsoftonline.com/common/discovery/v2.0/keys) don't include the `alg` value which according to the RFC is optional. This causes `token.decode_with_jwks(&jwkset)` to always fail here:
https://github.com/lawliet89/biscuit/blob/2cbe6ed02de6cf8790acd466b1234c13174f3f44/src/jws.rs#L164-L167

Since the field is optional, something like [this](https://github.com/ccakes/biscuit/commit/42b23075746b1bb66253819ba3a3065c525a263e) works to check it **if** the value is present.

If you'd accept this as a PR let me know

**Comment by lawliet89** [comment]
Sure. Please submit a PR.
