### ISSUE TITLE
Secret to implement Clone

### ISSUE THREAD

**Issue by laralex** [lawliet89/biscuit#159]
Is there a particular reason why `Secret` doesn't implement `Clone`? 

I just didn't want to create a `Secret` from a known public key string every request, but the project I'm contributing to requires `Clone` to pass precomputed data to existing functions.

**Comment by lawliet89** [comment]
No particular reason. I have fixed this omission on master branch. 

- If you cannot wait for `0.5.0`, you can use the master branch right now.
- However, there are a bunch of breaking changes that you might have to deal with. See the list of [PRs](https://github.com/lawliet89/biscuit/pulls?q=is%3Apr+is%3Aclosed+milestone%3Av0.5.0+label%3Abreaking) and [CHANGELOG](https://github.com/lawliet89/biscuit/blob/master/CHANGELOG.md).

**Comment by laralex** [comment]
Having it on stable release would be really cool, but I assume it would be a hassle for you to push the update to 0.4.0. I'll try 5.0.0 anyway, some breaking changes are really in my favour
