### ISSUE TITLE
`JWKSet` is not cloneable

### ISSUE THREAD

**Issue by Eric-Arellano** [lawliet89/biscuit#203]
Hello, thank you for an excellent library! This has been really helpful and I appreciate the JWK support.

It looks like `JWKSet` does not derive `Clone`:

https://github.com/lawliet89/biscuit/blob/9148092e2adb99781cb9ec86dd4180f67b69bd75/src/jwk.rs#L665-L670

However, `JWK` does:

https://github.com/lawliet89/biscuit/blob/9148092e2adb99781cb9ec86dd4180f67b69bd75/src/jwk.rs#L616-L630

Do you know if there is a particular reason for this, or it's only an oversight? I'd be happy to submit a small patch for 0.6.* if you'd be interested.

**Comment by lawliet89** [comment]
It's an oversight. Please submit a PR to add it in, if you have the time.

**Comment by lawliet89** [comment]
Had some time so I've opened and will merge in https://github.com/lawliet89/biscuit/pull/204 once tests pass.

**Comment by Eric-Arellano** [comment]
Thank you!
