### ISSUE TITLE
Elliptic curve based keys not available in decode_with_jwks

### ISSUE THREAD

**Issue by kgeorgy** [lawliet89/biscuit#256]
It seems that EC related algs are not supported when decoding using decode_with_jwks.

https://github.com/lawliet89/biscuit/blob/53e94cd41c50cda39fd7df0a0ba68f2d3b702130/src/jws/compact.rs#L201

Is there a plan to support that?

**Comment by Wicpar** [comment]
@kgeorgy if your problem is still ongoing you can use my fork in #310 :)

**Comment by kgeorgy** [comment]
@Wicpar Thank's for the fix. Even if I switched my stack away from Mosquitto (which used a plugin which used biscuit), that's great to see it could be an option. (But that's not the only reason for the switch)

**Comment by lawliet89** [comment]
Fixed by https://github.com/lawliet89/biscuit/pull/310
