### ISSUE TITLE
JWT RSA -> Chicken and egg problem

### ISSUE THREAD

**Issue by axos88** [lawliet89/biscuit#98]
To correctly decode & verify a JWT, one needs access to the header, so that the correct jwk can be looked up using the value of the "kid" claim. 
However to access the headers, one needs to correctly decode the jwt, using the correct key.

Actually the Decode process and the verification process should be separate, we should be able to access the decoded info without actually verifying the signature. Or at least the header.

**Comment by axos88** [comment]
at least this is the case for [auth0](www.auth0.com) tokens.

**Comment by lawliet89** [comment]
There is a method to extract out the header: [`unverified_header`](https://docs.rs/biscuit/0.0.8/biscuit/jws/enum.Compact.html#method.unverified_header).

You might want to make sure the key you get from extracting the header is in some sort of whitelist.

**Comment by axos88** [comment]
Yeah thanks. `Auth0` makes use of the `.well_known/jwks.json`, so it will be fetched from there :)

**Comment by lawliet89** [comment]
I'm closing this now because I think your issue is resolved. Please reopen this if you think otherwise.
